#!/bin/bash

# wget -O - https://raw.githubusercontent.com/DanieleCapponi/i2checks/master/grub 2>/dev/null | bash

git clone https://github.com/DanieleCapponi/i2checks.git 
cd i2checks
chmod 744 install_checks
./install_checks
cd .. && rm -r i2checks/
