#!/bin/bash

[[ $(id -u) -ne 0 ]] && echo -e "\nYou must be root" && return 0

G='\033[0;32m'
R='\033[0;31m'
W='\033[1;37m'

nagios='/usr/lib/nagios/plugins'
pl='plugins'

checks=$(ls -1 $pl)

echo -e "\nInstallig Icinga2 Modules:"

if [[ ! -d $nagios ]]; then
        mkdir -p $nagios && echo "[+] ${nagios} created"
        cp $pl/* $nagios/ && chmod 755 -R $nagios/
else
        cp $pl/* $nagios/ && chmod 755 -R $nagios/
fi

for c in $checks; do
        if [[ $(ls -l $nagios |grep $c |wc -l) -ne 0 ]]; then
                echo -e "${G}[+] Installed${W}  >  ${nagios}/${c}"
        else
                echo -e "[-] ${c} :: ${R}ERROR${W}. Check ${nagios}"
        fi


done

#rm -r ../i2checks
